version: "3"
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: jie
      POSTGRES_PASSWORD: pwd123
      POSTGRES_DB: cat_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"



      